#!/bin/bash

###########################
# Dependencies: sysstat
###########################

LOCK_FILE=/tmp/hdsleep.lock

usage(){
	echo Sends command to the given hdd to go to standby or sleep mode.
	echo
	echo "Usage: $(basename $0) hdd (standby|sleep)"
	exit 1
}

if [ $# -ne 2 ]; then
        usage
fi
if [ ! -e $1 ]; then
	usage
fi

# get hdd activity
iostat -x $1 5 2 > /tmp/iostat.log
cpu=$(sed '13!d' /tmp/iostat.log | cut -c118)
rm -f /tmp/iostat.log

if [ $cpu -eq 0 ]; then
    # exit if lock file found
    if [ -e $LOCK_FILE ]; then exit 0; fi

    logger "No activity in hdd $1."
    # hdd into sleep
    case $2 in
        standby)
            logger "Bring $1 to $2 mode."
            hdparm -y $1
            ;;    
        sleep)
            logger "Bring $1 to $2 mode."
            hdparm -Y $1
            ;;
        *)
            echo "Missing hdd stop mode."
            exit 1
            ;;
    esac    
    echo $(date) > $LOCK_FILE
else
    logger "Current cpu activity in hdd $1: $cpu"
    rm -f $LOCK_FILE
fi
