#!/bin/sh

csv=$(curl -s freegeoip.net/csv/)

ip=$(echo ${csv}| cut -d "," -f 1)
country=$(echo ${csv}| cut -d "," -f 2)
state=$(echo ${csv}| cut -d "," -f 4)
city=$(echo ${csv}| cut -d "," -f 6)
echo "IP: ${ip}\nCountry: ${country}\nState: ${state}\nCity: ${city}"
