#!/bin/sh

set -e

VERSION_FILE=/tmp/turtl-version

version=$( wget https://turtlapp.com -O turtlhome > /dev/null 2>&1 && cat turtlhome | grep -oE "turtl-linux64-[0-9].[0-9].[0-9]" | uniq | grep -Eo "[0-9].[0-9].[0-9]*$" )

if [ -f $VERSION_FILE ]; then
	if [ "$(cat $VERSION_FILE)" != "$version" ]; then
		echo $version > $VERSION_FILE
		curl -H "Content-Type: application/json" -X POST -d '{"recipient":"andoni.delolmo@gmail.com","subject":"Turtl new version '"$version"'","message":"Turtl has released the version '"$version"'. https://turtlapp.com/download/"}' http://localhost:8080/mails
	fi
else
	echo $version > $VERSION_FILE
fi
