#!/bin/sh

set -e

DIR=/var/local/turtl-check
VERSION_FILE=$DIR/turtl-version
WEBSITE=https://turtlapp.com

version=$( wget $WEBSITE -O turtlhome > /dev/null 2>&1 && cat turtlhome | grep -oE "turtl-linux64-[0-9].[0-9].[0-9]" | uniq | grep -Eo "[0-9].[0-9].[0-9]*$" )

if [ -f $VERSION_FILE ]; then
	if [ "$(cat $VERSION_FILE)" != "$version" ]; then
		echo $version > $VERSION_FILE
		curl -H "Content-Type: application/json" -X POST -d '{"recipient":"andoni.delolmo@gmail.com","subject":"Turtl new version '"$version"'","message":"Turtl has released the version '"$version"'. '"$WEBSITE"'/download/"}' http://localhost:9080/mails
	fi
else
	mkdir -p $DIR
	echo $version > $VERSION_FILE
fi
