#!/bin/sh

set -e

TMP=/tmp/dpkg-build
version=$(cat VERSION)
size=$(du -csh package/ | sed '1!d' | grep -oe "^[0-9]*")

echo "Building version $version..."

setup(){
	rm -Rf $TMP
	mkdir -p /tmp/release
	mkdir -p $TMP
	cp -R package/* $TMP
	sed 's/\[\[version\]\]/'${version}'/g;s/\[\[size\]\]/'${size}'/g' package/DEBIAN/control > $TMP/DEBIAN/control
}

setup
fakeroot dpkg-deb --build -z9 $TMP /tmp/release

echo done