#!/bin/bash

TMP=/tmp/dpkg-hdsleep
version=`cat VERSION`

echo "Building version $version..."

# Architectures: i386, amd64, armle

setup(){
	rm -Rf $TMP
	mkdir -p /tmp/release
	mkdir -p $TMP
	cp -R package/* $TMP
	sed 's/\[\[version\]\]/'${version}'/g' package/DEBIAN/control > $TMP/DEBIAN/control
	chown root:root -R $TMP
}

setup
dpkg -b $TMP /tmp/release/hdsleep_$version.deb
#setup
#dpkg -b $TMP /tmp/release/hdsleep_1.0.0_i386.deb

echo done
