#!/bin/bash

TMP=/tmp/dpkg-hdsleep
version=$(cat VERSION)
size=$(du -csh package/ | sed '1!d' | grep -oe "^[0-9]*")

echo "Building version $version..."

# Architectures: i386, amd64, armle

setup(){
	rm -Rf $TMP
	mkdir -p /tmp/release
	mkdir -p $TMP
	cp -R package/* $TMP
	sed 's/\[\[version\]\]/'${version}'/g;s/\[\[size\]\]/'${size}'/g' package/DEBIAN/control > $TMP/DEBIAN/control
	chown root:root -R $TMP
}

setup
dpkg-deb -b -z9 $TMP /tmp/release

echo done
