#!/bin/bash

DELUGE_HOME=/home/deluge
DELUGE_LOG_DIR=/var/log/deluge
DELUGE_PORT=9092
HTTPS_ENABLE=true

# http://dev.deluge-torrent.org/wiki/UserGuide/Service/systemd
echo "Creating \`deluge' user with home directory \`$DELUGE_HOME' ..."
adduser --system --gecos "Deluge Service" --disabled-password --group --home $DELUGE_HOME deluge > /dev/null 2>&1

if [ ! -d $DELUGE_LOG_DIR ]; then
	mkdir $DELUGE_LOG_DIR
	chown deluge.deluge $DELUGE_LOG_DIR
fi

rm -f /etc/init.d/deluged

mkdir $DELUGE_HOME/incoming $DELUGE_HOME/torrents $DELUGE_HOME/torrents_add $DELUGE_HOME/temp
mkdir -p $DELUGE_HOME/.config/deluge/ssl
echo "Creating SSL Certificate ..."
openssl req -new -x509 -nodes -out $DELUGE_HOME/.config/deluge/ssl/deluge.cert -keyout $DELUGE_HOME/.config/deluge/ssl/deluge.pkey -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=example.com" > /dev/null 2>&1
chmod 600 $DELUGE_HOME/.config/deluge/ssl/deluge.*

echo "Creating deluge web configuration \`$DELUGE_HOME/.config/deluge/web.conf' ..."
cat > $DELUGE_HOME/.config/deluge/web.conf <<EOF
{
  "file": 1, 
  "format": 1
}{
  "sidebar_show_zero": false, 
  "show_session_speed": false, 
  "pwd_sha1": "660ca4dd14ee1aec5b7e1bc9dc8e42dfaf7848af", 
  "show_sidebar": true,
  "enabled_plugins": [], 
  "base": "/", 
  "first_login": false, 
  "theme": "gray", 
  "pkey": "ssl/deluge.pkey", 
  "cert": "ssl/deluge.cert", 
  "session_timeout": 3600, 
  "https": $HTTPS_ENABLE, 
  "default_daemon": "localhost:58846", 
  "sidebar_multiple_filters": true, 
  "pwd_salt": "dc78fc761bedd4c73273d20d7bdd166c0606f745", 
  "port": $DELUGE_PORT
}
EOF
echo "Creating deluge core configuration \`$DELUGE_HOME/.config/deluge/core.conf' ..."
cat > $DELUGE_HOME/.config/deluge/core.conf <<EOF
{
  "file": 1,
  "format": 1
}{
  "info_sent": 0.0,
  "lsd": true,
  "max_download_speed": -1.0,
  "send_info": false,
  "natpmp": true,
  "move_completed_path": "$DELUGE_HOME/incoming",
  "peer_tos": "0x00",
  "enc_in_policy": 1,
  "queue_new_to_top": false,
  "ignore_limits_on_local_network": true,
  "rate_limit_ip_overhead": true,
  "daemon_port": 58846,
  "torrentfiles_location": "$DELUGE_HOME/torrents",
  "max_active_limit": 8,
  "geoip_db_location": "/usr/share/GeoIP/GeoIP.dat",
  "upnp": true,
  "utpex": true,
  "max_active_downloading": 10,
  "max_active_seeding": 4,
  "allow_remote": false,
  "outgoing_ports": [
    0,
    0
  ],
  "enabled_plugins": [],
  "max_half_open_connections": 50,
  "download_location": "$DELUGE_HOME/temp",
  "compact_allocation": false,
  "max_upload_speed": -1.0,
  "plugins_location": "$DELUGE_HOME/.config/deluge/plugins",
  "max_connections_global": 200,
  "enc_prefer_rc4": true,
  "cache_expiry": 60,
  "dht": true,
  "stop_seed_at_ratio": true,
  "stop_seed_ratio": 4.0,
  "max_download_speed_per_torrent": -1,
  "prioritize_first_last_pieces": false,
  "max_upload_speed_per_torrent": -1,
  "auto_managed": true,
  "enc_level": 2,
  "copy_torrent_file": true,
  "max_connections_per_second": 20,
  "listen_ports": [
    6881,
    6891
  ],
  "max_connections_per_torrent": -1,
  "del_copy_torrent_file": false,
  "move_completed": true,
  "autoadd_enable": true,
  "proxies": {
    "peer": {
      "username": "",
      "password": "",
      "hostname": "",
      "type": 0,
      "port": 8080
    },
    "web_seed": {
      "username": "",
      "password": "",
      "hostname": "",
      "type": 0,
      "port": 8080
    },
    "tracker": {
      "username": "",
      "password": "",
      "hostname": "",
      "type": 0,
      "port": 8080
    },
    "dht": {
      "username": "",
      "password": "",
      "hostname": "",
      "type": 0,
      "port": 8080
    }
  },
  "dont_count_slow_torrents": false,
  "add_paused": false,
  "random_outgoing_ports": true,
  "max_upload_slots_per_torrent": -1,
  "new_release_check": false,
  "enc_out_policy": 1,
  "seed_time_ratio_limit": 7.0,
  "remove_seed_at_ratio": false,
  "autoadd_location": "$DELUGE_HOME/torrents_add",
  "max_upload_slots_global": 4,
  "seed_time_limit": 180,
  "cache_size": 512,
  "share_ratio_limit": 4.0,
  "random_port": true,
  "listen_interface": ""
}
EOF
echo "Creating keepalive script in \`$DELUGE_HOME/keepalive' ..."
cat > $DELUGE_HOME/keepalive <<EOF
#!/bin/bash

process=deluged
makerun="service deluge start"

if ps ax | grep -v grep | grep \$process > /dev/null; then
        exit
else
        logger "Start deluge service."
        exec \$makerun
fi            
EOF
chmod u+x $DELUGE_HOME/keepalive
chown deluge.deluge -R $DELUGE_HOME

if [ "$HTTPS_ENABLE" == "true" ]; then
	echo "Starting deluge service on \`https://localhost:$DELUGE_PORT' ..."
else 
	echo "Starting deluge service on \`http://localhost:$DELUGE_PORT' ..."
fi
service deluge start > /dev/null 2>&1
echo "Deluge logs are located in \`$DELUGE_LOG_DIR'."